FROM arm64v8/rust:slim-bookworm
WORKDIR /app
RUN mkdir -p /app/src
RUN echo "fn main() {println!(\"if you see this, the build broke\")}" > src/main.rs
COPY ./Cargo.toml ./
COPY ./Cargo.lock ./
COPY ./benches ./benches
RUN cargo fetch
RUN cargo build --release

COPY ./src ./src
RUN cargo build --release

FROM arm64v8/debian:bookworm-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates \
 && update-ca-certificates \
 && apt-get clean autoclean \
 && apt-get autoremove --yes \
 && rm -rf /var/lib/{apt,dpkg,cache,log}/

WORKDIR /app
RUN mkdir -p /app/target/release
COPY ./static ./static
COPY ./1hosts_pro.txt ./
COPY --from=0 /app/target/release/dns /app/target/release/

EXPOSE 53/udp
ENTRYPOINT ["./target/release/dns"]
